#!/usr/bin/env bash
#Call scp

sudo apt-get update -y
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart
