#!/usr/bin/env bash
# asda asd asfd adsf 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Error 404" > /var/www/html/new_404.html
sudo sed -i 'rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;\n' /etc/nginx/sites-available/default
sudo sed -i 'error_page 404 /new_404.html; \nlocation = /new_404.html \n{\nroot /var/www/html/;\ninternal; \n}' /etc/nginx/sites-available/default
sudo sed -i 'add_header X-Served-By $hostname;\n' /etc/nginx/sites-available/default
sudo service nginx restart
