#!/usr/bin/env bash
# asd asd asd as
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update
sudo apt-get install haproxy -y

echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.196.90.236:80 check\n\tserver web2 34.73.156.98:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg

service haproxy restart
