#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9 print Hi
i=0

while [ $i -lt 20 ]
do
    ((i++))
    echo $i
    case $i in
        4)
        echo "bad luck from China"
        ;;
        9)
        echo "bad luck from Japan"
        ;;
        17)
        echo "bad luck from Italy"
        ;;
    esac
done
